### ISSUE TITLE
Reload not work

### ISSUE THREAD

**Issue by miladmeidanshahi** [vuejs-templates/webpack#1211] opened 2017-12-31 14:22 UTC
Hi, i installed latest vue-cli and vue webpack and start my project via `npm run dev` and i changed any file but hot reload not working how can i get logs ?

**Comment by LinusBorg** [comment] 2017-12-31 14:43
HMR often doesn't work in paths that contain special characters (e.g. `(` ), or when the project is in a folder controlled by another app / system (e.g. dropbox/googledrive, Vagrant, VirtualBox).

If none of that applies, you would have to ask the webpack community how to debug this, we don't really know the webpack internals at pley here.

Closing this as it's also a duplicate of #1209

**Closed by LinusBorg** 2017-12-31 14:43 UTC

**Comment by miladmeidanshahi** [comment] 2018-01-01 08:34
@LinusBorg Thanks
by changing `poll` option in `config/index.js` to `true` it works.
