### ISSUE TITLE
Webpack 4 ?

### ISSUE THREAD

**Issue by gplusdotgr** [vuejs-templates/webpack#1373] opened 2018-05-03 15:38 UTC
Are there plans to move to webpack 4.x? There are plenty of changes. (I just did this myself and there are issues like source maps not working etc)

**Comment by ChadTaljaardt** [comment] 2018-05-03 18:09
dupe of https://github.com/vuejs-templates/webpack/issues/1280

Also here is a working pr : https://github.com/vuejs-templates/webpack/pull/1369

You can use it by running 

```js 
vue init noamkfir/webpack#webpack-4 project
```

**Comment by ChadTaljaardt** [comment] 2018-05-04 12:50
Can we close this issue as its a duplicate of the above?

**Closed as completed** 2018-05-04 12:50 UTC
