### ISSUE TITLE
Press CTRL+C can not stop the progress

### ISSUE THREAD

**Issue by ChangeZhang** [vuejs-templates/webpack#1153] opened 2017-12-07 18:00 UTC
[gif link](https://github.com/ChangeZhang/vue-seller-demo/blob/master/test4.gif)

![image](https://user-images.githubusercontent.com/6948367/33730596-6a002ea0-dbbb-11e7-8443-42e863aa0313.png)

**Comment by LinusBorg** [comment] 2017-12-08 08:30
Hm. I'm not on High Sierra yet, and can't reproduce anything like this on my MBPro ...

**Comment by PengLL** [comment] 2017-12-11 08:57
I  also met this problem on win7，and I guess the reason is that some kind of Application  forbids our program to stop the progress

**Comment by LinusBorg** [comment] 2017-12-11 14:55
Closing this since this is not reproducible for me, and I have no Idea what we can do about this,

If somone can provide further useful input, feel free to comment or open a new issue.

**Closed by LinusBorg** 2017-12-11 14:55 UTC
