### ISSUE TITLE
npm run build blank display

### ISSUE THREAD

**Issue by Erkajp** [vuejs-templates/webpack#310] opened 2016-10-10 19:07 UTC
when npm run dev display correctly, but all link like css, or js build by webpack load completly
and i found error "ReferenceError: webpackJsonp is not defined"

this my index html:
[look](http://prnt.sc/cs7q0f)
and this main js :

import Vue from 'vue'
import store from './store'
import router from './router'
import { sync } from 'vuex-router-sync'
import App from './App'

sync(store, router)

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  store,
  render: h => h(App)
})
i use standalone type

**Comment by chrisvfritz** [comment] 2016-10-11 07:22
Does this also happen for you on a freshly-generated project?

**Comment by Erkajp** [comment] 2016-10-11 07:40
yes this happen, i try with apache and nginx, and i try to copy paste code to other file still same.
only `npm run dev ` display correctly

**Comment by joshle** [comment] 2016-10-11 07:53
I have the same problem,

**Comment by chrisvfritz** [comment] 2016-10-11 18:29
Are you sure you're actually serving the compiled files `dist` directory?

**Comment by kiwina** [comment] 2016-10-12 05:44
just tried a blank out of the box project and run: npm run dev 
there is a problem with .vue files

**Comment by LinusBorg** [comment] 2016-10-12 12:05
> just tried a blank out of the box project and run: npm run dev 
there is a problem with .vue files

The issue that you commented on is not about problems with `npm run dev`, it's about the production build.

If you have a problem with that, please open a separate issue.

**Comment by LinusBorg** [comment] 2016-10-12 17:14
I just generated a new project, ran `npm run build` and started [http-server](https://www.npmjs.com/package/http-server) in `/dist/`

Default page shows without any problems.
![bildschirmfoto 2016-10-12 um 19 13 35](https://cloud.githubusercontent.com/assets/1444526/19320060/0786c164-90b0-11e6-89af-56470202e5d9.png)

**Comment by LinusBorg** [comment] 2016-10-12 23:01
I will close this now. If you can provide a reproduction, we can re-open.

**Closed by LinusBorg** 2016-10-12 23:01 UTC
Labels: need repro

**Comment by woozyking** [comment] 2017-02-02 00:11
I encounter the same issue from time to time as well, where the `manifest` gets transferred, but app or other component (by vue-router) js files get "stuck", and leads to a forever blank screen.

Not sure exactly why though

**Comment by AngeloAnolin** [comment] 2017-03-19 02:06
I think I am also having the same issue as @woozyking is encountering.

The only difference is that the dist files after building, I am serving via Windows IIS (Internet Information Services).

I do have a valid and working web.config file in the dist folder.

The project I have tries to call Authentication (via Auth0) and then after checking the authentication, nothing is happening. It seems that the router is not routing or serving the correct routes as required.

**Comment by abotsi** [comment] 2017-06-28 11:03
Hey, 
Same problem as @woozyking here. Does anyone understand what could be happening ?

**Comment by ssshooter** [comment] 2017-07-14 15:09
@AngeloAnolin @abotsi 
started http-server and visit 127.0.0.1 is OK,but 127.0.0.1/index.html is blank.
i think the problem is related to vue-router,‘index.html’ must be omitted

**Comment by flickyiyo** [comment] 2017-07-20 13:33
In dist/index.html change every `/static/` to  `static/`

**Comment by martijnhiemstra** [comment] 2017-07-29 10:09
It's just like flickyiyo said, all the url's are absolute and should be relative. Someone at VueJS has made a huge mistake making all the url's absolute. In my case I have Ubuntu on my computer and when I open the index.html the url's to the Javascript files start with / meaning the browser wants to look for the Javascript files on the root of my harddisk. Someone at VueJS really needs to wake up and fix this. Relative url's and nothing else.

**Comment by tiagomatosweb** [comment] 2017-08-20 02:46
Guys, I think you are missing that SPA is not server side rendering. At least for the majority. So, when you access /anything your web server won't redirect it to index.html. However, if you click on any vuejs router link, it will work due to the fact that the javascript got in action, but not the server side.

To solve this, use .htaccess and redirect all requests to index.html like so

```
<ifModule mod_rewrite.c>
    RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</ifModule>
```

Hope it helps someone!

**Comment by IvanRusli777** [comment] 2017-09-11 12:46
im having the same issue, please help this is frustrating

**Comment by tiagomatosweb** [comment] 2017-09-11 23:07
@IvanRusli777 have you set up the rewrite rule?

**Comment by wixys** [comment] 2017-12-13 20:37
After I run "npm run build", I got this tip in the console:

Build complete.

Tip: built files are meant to be served over an HTTP server. Opening index.html over file:// won't work.

In my local server, npm run dev works fine, but after upload the project on Apache server, installed node_modules (npm install) and I run "npm run build", I got the tip in the console and a blank page, no errors in dev console in my browser

The path on the server (Apache) is: /mydomainproject/public/projects files:

build
config
dist
node_modules
src
static
.babelrc
.editorconfig
.postcssrc.js
index.html
package.json
package-lock.json
This is my public/config/index.js

build: {
    // Template for index.html
    index: path.resolve(__dirname, '../dist/index.html'),

    // Paths
    assetsRoot: path.resolve(__dirname, '../dist'),
    assetsSubDirectory: 'static',
    assetsPublicPath: '/',
I've changed assetsPublicPath: '/' to assetsPublicPath: './', also I tried assetsPublicPath: './public', but still not work.

Please, someone can help me?

Thanks!

**Comment by wixys** [comment] 2017-12-14 11:13
I'm really scared, I'm building a web app using VueJs on local server and everything working fine after run "npm run dev", but after run build on production server (Apache) I got blank page... nobody knows about this problem... I've changed config/index.js, adding relative paths, ./, /, even absolute path (I never work with absolute paths), I've asked in Stackoverflow, no answers... Also, there are no errors in the console log browser.

**Comment by AngelKMB** [comment] 2017-12-14 11:50
Hi,

I am having the same problem as wixys. Can anyone help?

**Comment by wixys** [comment] 2017-12-14 12:29
I tried with a Vue fresh installation, I got the same blank page and tip in the console after run "npm run build" on a production server.

Tip: built files are meant to be served over an HTTP server.
Opening index.html over file:// won't work.

**Comment by IvanRusli777** [comment] 2017-12-15 01:56
@tiagomatosweb yes, its all working now. my case is solved by changing my nginx server config and directing it to dist folder, so stupid of me

**Comment by AngelKMB** [comment] 2017-12-15 11:32
works fine too

**Comment by Severin-THIRIOT** [comment] 2017-12-29 12:37
I have the same issue, I work on this for 2 days it's very frustrating

**Comment by mirhat** [comment] 2018-01-01 22:43
@Severin-THIRIOT  Did you find cause of this issue?

**Comment by lawrence615** [comment] 2018-01-08 13:46
Pointing the Nginx root to dist directory worked for me as well. Well explained in this tutorial: https://medium.com/@Web_Bailey/deploy-a-vuejs-app-with-digitalocean-fd6e7af07e40

**Comment by neculaionutni** [comment] 2018-02-02 13:14
The best solution I could come up with was to copy the code from `dist/index.html` to `index.html` from the root project and then just changed the `/static/...` path to `your_main_folder/static`, your_main_folder being the subdirectory from you deployment server. Or if you have it in your root you just have to stick with `static/...`. Nothing to do with server configuration, as simple as that.

**Comment by tetreault** [comment] 2018-02-24 18:38
Similarly, I am experimenting with vue on an ubuntu ec2 micro i set up (empty except for empty node project skeleton and nginx). I have an express node server that is going to serve up the final index.html. i run `vue init webpack-simple project-name` and then `npm install` to get the dependencies. Then I run `npm run build` inside the folder vue-cli created, it completes successfully with no warnings or errors. 

The Node express server serves up the index.html just fine, but the index.html file is empty. Furthermore the `dist` folder is missing, thus `dist/build.js` is 404. 

Am I missing a step here? New to vue, so apologies if its something obvious! Thanks in advance for any help!

Screenshots: 
<img width="556" alt="screenshot 2018-02-24 13 32 00" src="https://user-images.githubusercontent.com/5934354/36633682-d9ef810e-1967-11e8-84aa-5f74b3f15085.png">

<img width="330" alt="screenshot 2018-02-24 13 35 19" src="https://user-images.githubusercontent.com/5934354/36633688-dc5f336c-1967-11e8-89c8-e030fae29ccb.png">

<img width="780" alt="screenshot 2018-02-24 13 35 35" src="https://user-images.githubusercontent.com/5934354/36633689-e00007bc-1967-11e8-85f2-f9160b62b82f.png">

Versions: 
vue-cli: 2.9.3
node: v9.6.1
npm: 5.6.0

**Comment by ghost** [comment] 2018-05-05 10:30
hey guys, i had the same issue. Blank page for production build even though all files were properly served from the dist folder (including index.html) by nginx. Turns out i was using wrong Vue build for my production build.
I had "vue.runtime.min.js" set as an alias to vue$ in webpack config. Switching it to "vue.min.js" resolved my problem.

**Comment by schiu-choice** [comment] 2018-05-31 23:51
Under config folder, index.js. update the path to assets. From default "/" to "./"

And build again! 

works for me!

![help](https://user-images.githubusercontent.com/30106029/40813988-1458e474-6581-11e8-82ed-c17c8d9b3f3d.jpg)

**Comment by fnoori** [comment] 2018-06-19 15:03
If anyone else is having this problem.
I fixed mine by removing the "/" from the assetsPublicPath in ```config/index.js```

<img width="570" alt="screen shot 2018-06-19 at 9 02 08 am" src="https://user-images.githubusercontent.com/16112234/41605870-9802a25c-739f-11e8-97b3-18e00b3c97ad.png">

**Comment by vdraceil** [comment] 2018-07-05 12:39
Any other solution besides adding a dot or clearing out `build.assetsPublicPath`? .. because those two don't work for me.

However, removing `mode: 'history'` from the VueRouter initialization works, but I do not want hashtags in my URL..

**Comment by ManuelSchmitzberger** [comment] 2018-07-13 09:54
My problem was that the webserver was configured wrongly. So the CSS and JS files cannot be found.
Simple check this via the browser debugger console.



put that in your nginx.conf::

```
http {
   server {
        listen 80;
        server_name yourservername.com;
        root html/path_to_your_project;

        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
```

**Comment by 9nix00** [comment] 2018-07-31 13:10
OK, I found two reason may cause blank display when use build.
I have tested so many times, and finally found them, it cost me one day! unbelievable!!!
1. `assetsPublicPath`,like @schiu-choice said. 
2.  your Router use `history` mode. disable this feature will works. but I don't know why, wish team member can fix it. I am not familiar with Vue.

**Comment by vladkazakoff** [comment] 2018-08-03 04:25
I found a solution for build production ver. outside server root folder **with history** mode:
1. in assetsPublicPath add dot like @schiu-choice said;
2. in your vue-router add your specific root folder in all routes.
Example:
your vue production version host in http://test.test/mainVue
so, your main route:
```
routes: [
    {
      path: '/mainVue/',
      name: 'mainVue',
      component: mainComponent,
    }
```

**Comment by renaudham** [comment] 2018-08-08 12:59
HI

one note for the people putting the dist in a local apache server Xampp/Wampp
you need to put your index.html as index.php
and put your files in the root of you vhost.
Then all will run well...

**Comment by StudioRyuLLC** [comment] 2018-09-21 14:45
@KazakoffJunior...thank you! Your solution resolved the same issue I was having. :)

**Comment by 0xchetan** [comment] 2018-11-02 20:31
Pointing the root location of server to /dist folder in nginx config worked for me.

**Comment by ahmedsamir93** [comment] 2018-11-15 15:42
> إذا كان أي شخص آخر لديه هذه المشكلة. 
> أصلحت الألغام عن طريق إزالة "/" من الموجوداتالعامةالعامة`config/index.js`
> 
> <img alt="لقطة شاشة 2018-06-19 في 9 02 08 ص" width="570" src="https://user-images.githubusercontent.com/16112234/41605870-9802a25c-739f-11e8-97b3-18e00b3c97ad.png">

Thank you it works well

**Comment by ahmedsamir93** [comment] 2018-11-15 15:53
> If anyone else is having this problem.
> I fixed mine by removing the "/" from the assetsPublicPath in `config/index.js`
> 
> <img alt="screen shot 2018-06-19 at 9 02 08 am" width="570" src="https://user-images.githubusercontent.com/16112234/41605870-9802a25c-739f-11e8-97b3-18e00b3c97ad.png">

Thank you it works well

**Comment by 3ehrang** [comment] 2018-11-20 19:11
Anyone who uses wamp server you can create virtualhost for the project like these configs and run your lcoalhost `http://vueapp.local` works for me

```
<VirtualHost *:80>
    DocumentRoot "E:\wamp\www\vueapp\dist"
    ServerName vueapp.local
    <directory "E:\wamp64\www\vueapp\dist">
        DirectoryIndex index.html
        AllowOverride all
        Order Allow,Deny
        Allow from all
    </directory>
</VirtualHost>
```

**Comment by tvkit** [comment] 2019-09-05 22:46
_http-server_ wasn't working, but the following worked for me:

```
npm install -g serve
# -s flag means serve it in Single-Page Application mode
# which deals with the routing problem below
serve -s dist

```
Details here:
[Preview Locally @ vuejs.org](https://cli.vuejs.org/guide/deployment.html#previewing-locally)

**Comment by BartusZak** [comment] 2019-11-11 20:47
`Invalid options in vue.config.js: "assetsPublicPath" is not allowed`
disabling `history` didn't help either
any other solutions?

**Comment by amucunguzi** [comment] 2019-11-16 13:29
@vdraceil mentioned:

> However, removing mode: 'history' from the VueRouter initialization works, but I do not want hashtags in my URL..

From VueJs documentation: 

> Not to worry: To fix the issue, all you need to do is add a simple catch-all fallback route to your server. If the URL doesn't match any static assets, it should serve the same index.html page that your app lives in. (https://router.vuejs.org/guide/essentials/history-mode.html#html5-history-mode)

So, all you need to do to enable history mode is add a catch-all route:

```
{
   path: '*',
   name: 'catchAll',
   component: Home
}
```
**NOTE**: this catch-all route should go at the bottom -- after all other routes (otherwise, all requests will go to it).

**Comment by bties-ogawa** [comment] 2020-02-28 00:42
i using vue cli v3.4.0 with history mode.
in my case, it was resolved by to set empty `publicPath` on `vue.config.js`

```
module.exports = {
  publicPath: ''
}
```

**Comment by harishcsha** [comment] 2020-03-21 14:45
Try this, 
Open --> config > index.js file
there will be many configuration, but our aim is to change only the **assetsPublicPath** in **build** object from **assetsPublicPath: '/'** to **assetsPublicPath: '',** 
```
dev: {
    assetsPublicPath: '/',
  },

  build: {
    assetsPublicPath: '',
  }
```
**NOTE:** do not change anything inside **dev** object let it be as it is.

**Comment by bala-techguy** [comment] 2020-04-20 20:21
> i using vue cli v3.4.0 with history mode.
> in my case, it was resolved by to set empty `publicPath` on `vue.config.js`
> 
> ```
> module.exports = {
>   publicPath: ''
> }
> ```

After hours of struggle. This worked for me.

**Comment by Chinyoka1** [comment] 2020-08-16 09:44
Hey, I'm using Vue as a SPA in a Laravel project. Does anyone know how to fix it in that case?

**Comment by ghost** [comment] 2021-03-23 17:49
> > i using vue cli v3.4.0 with history mode.
> > in my case, it was resolved by to set empty `publicPath` on `vue.config.js`
> > ```
> > module.exports = {
> >   publicPath: ''
> > }
> > ```
> 
> After hours of struggle. This worked for me.

Where is vue.config.js? I don't see this file.

**Comment by mikkybang** [comment] 2021-04-08 16:41
So I have had this error for a while, I tried all the proposed solutions above but none seemed to work.
Then I noticed that in development, there was a "you may have an infinite update loop in a component render function" warning, which I had been ignoring, after fixing the component, npm run build started to work well.

I hope this helps somebody

**Comment by rvk220** [comment] 2021-05-14 00:05
> In dist/index.html change every `/static/` to `static/`

Great, your advice is a real lifesaver! However, there's also a need to fix paths for images. I found the following way just by intuition, and it works well: in the file **/dist/js/app.a4b721c1.js**, replace **c.p = "/"** by **c.p = ""**. If not to do this, img elements (pictures) will not be displayed.

**Comment by burnquist** [comment] 2021-06-13 15:46
**cannot solve for me imade devedencies like this :**                                                                                                         
    "@babel/core": "^7.12.10",
    "@vue/cli-plugin-babel": "^4.5.9",
    "@vue/cli-plugin-e2e-nightwatch": "^4.5.9",
    "@vue/cli-plugin-eslint": "^4.5.9",
    "@vue/cli-plugin-unit-jest": "^4.5.9",
    "@vue/cli-service": "^4.5.9",
**my mode like this :**                                                                                                                                                                export default new Router({
  mode: 'history', // https://router.vuejs.org/api/#mode
  linkActiveClass: 'active',
  scrollBehavior: () => ({ y: 0 }),

  routes: configRoutes()
}),
 
**On vue.config.js** like this  
publicPath: process.env.NODE_ENV === 'production'
    ? './dist/'
    : '/' 

please help this my problem in situasion ......

**Comment by amiria703** [comment] 2021-08-28 04:59
For future reference of others:
As the things these guys said became old, if you have the same problem, look [here](https://cli.vuejs.org/config/#vue-config-js) and [here](https://cli.vuejs.org/config/#publicpath).

**Comment by amiria703** [comment] 2021-08-28 05:00
> > > i using vue cli v3.4.0 with history mode.
> > > in my case, it was resolved by to set empty `publicPath` on `vue.config.js`
> > > ```
> > > module.exports = {
> > >   publicPath: ''
> > > }
> > > ```
> > 
> > 
> > After hours of struggle. This worked for me.
> 
> Where is vue.config.js? I don't see this file.

I know it's too late, but see [this](https://github.com/vuejs-templates/webpack/issues/310#issuecomment-907570413).

**Comment by changefirst** [comment] 2021-09-01 09:19
I fixed this problem by adding dots to beginnibg of every path of linked files in index.html in dist folder. 

     Before:  

   `<link href="/css/app.7094705d.css" rel="preload" as="style" />
    <link href="/js/app.f0dc6036.js" rel="preload" as="script" />
    <link href="/js/chunk-vendors.df638b66.js" rel="preload" as="script" />
    <link href="/css/app.7094705d.css" rel="stylesheet" />
    ........
    <script src="/js/chunk-vendors.cfe8a783.js"></script>
    <script src="/js/app.1cf2902b.js"></script>
`
    
    After: 
    
    `<link href="./css/app.7094705d.css" rel="preload" as="style" />
    <link href="./js/app.f0dc6036.js" rel="preload" as="script" />
    <link href="./js/chunk-vendors.df638b66.js" rel="preload" as="script" />
    <link href="./css/app.7094705d.css" rel="stylesheet" />
    .......
    <script src="./js/chunk-vendors.cfe8a783.js"></script>
    <script src="./js/app.1cf2902b.js"></script>
    
    `
    
    then it showed every thing

**Comment by Hashasin** [comment] 2021-12-20 06:39
> Does this also happen for you on a freshly-generated project?

yes

**Comment by segunmayor** [comment] 2022-06-11 23:49
> Guys, I think you are missing that SPA is not server side rendering. At least for the majority. So, when you access /anything your web server won't redirect it to index.html. However, if you click on any vuejs router link, it will work due to the fact that the javascript got in action, but not the server side.
> 
> To solve this, use .htaccess and redirect all requests to index.html like so
> 
> ```
> <ifModule mod_rewrite.c>
>     RewriteEngine On
>   RewriteBase /
>   RewriteRule ^index\.html$ - [L]
>   RewriteCond %{REQUEST_FILENAME} !-f
>   RewriteCond %{REQUEST_FILENAME} !-d
>   RewriteRule . /index.html [L]
> </ifModule>
> ```
> 
> Hope it helps someone!
This helped actually

**Comment by AnishKumar-12345** [comment] 2023-02-21 13:18
> Try this, Open --> config > index.js file there will be many configuration, but our aim is to change only the **assetsPublicPath** in **build** object from **assetsPublicPath: '/'** to **assetsPublicPath: '',**
> 
> ```
> dev: {
>     assetsPublicPath: '/',
>   },
> 
>   build: {
>     assetsPublicPath: '',
>   }
> ```
> 
> **NOTE:** do not change anything inside **dev** object let it be as it is.

Hi it's really worked for me thanks

**Comment by freddy24** [comment] 2023-02-23 01:39
> 

not work for me. ,sad

**Comment by pierrelouisguichard** [comment] 2023-04-11 21:42
"## Solution
When using the dist directory
add base: ‘./’ into vite.config.js (or vite.config.ts)

import { defineConfig } from 'vite'
import vue from '[@vitejs/plugin-vue](http://twitter.com/vitejs/plugin-vue)'
export default defineConfig({
  plugins: [vue()],
  base: './', // added
})
Build in this state"

https://medium.com/geekculture/2022-vite-vue-screen-goes-white-when-deploying-9dcb9fc5b987
