### ISSUE TITLE
building for production...cp: no such file or directory: static/*

### ISSUE THREAD

**Issue by vaske** [vuejs-templates/webpack#433] opened 2017-01-05 15:43 UTC
I just followed up instructions written and tried to run `npm run build` and got this error 
    
      building for production...cp: no such file or directory: static/*

however I see generated output in console but files are not written on disk, I use OS.
Any ideas what might be wrong? Should I update config files or something?

**Comment by myst729** [comment] 2017-01-16 11:49
Initially the folder is empty (except a `.gitkeep`). So that's correct - `*` matches nothing. Once you put something in it, images or whatever, the error may go away.

**Comment by posva** [comment] 2017-01-17 08:54
duplicate of #401

**Comment by splosch** [comment] 2017-02-01 07:49
I'm puzzled by the same behavior.

The console output suggests there are files generated, where are those files? I suppose they should be added to the static folder - right?

**Comment by ianwalter** [comment] 2017-02-07 16:52
@vaske Upgrading `shelljs` to `0.7.6` fixed it for me.

**Comment by kazupon** [comment] 2017-02-15 06:40
Close (in-activity)

**Closed by kazupon** 2017-02-15 06:40 UTC
