### ISSUE TITLE
vue-cli · [.babelrc] Missing helper: "if_eq"

### ISSUE THREAD

**Issue by zslucky** [vuejs-templates/webpack#1079] opened 2017-11-17 00:42 UTC
Versions: 

vue-cli: 2.9.1
os: mac 10.12.6
node: 6.11.0
npm: 3.10.10

```bash
$ vue init webpack test-project

? Project name test-project
? Project description A Vue.js project
? Author zslucky <zsney.lzhou@gmail.com>
? Vue build standalone
? Install vue-router? Yes
? Use ESLint to lint your code? Yes
? Pick an ESLint preset Standard
? Setup unit tests Yes
? Pick a test runner jest
? Setup e2e tests with Nightwatch? Yes
   vue-cli · [.babelrc] Missing helper: "if_eq"
```

hmm... any wrong with me?

**Comment by LinusBorg** [comment] 2017-11-19 09:38
I can't reproduce this, no idea how this happens for you.

**Comment by zslucky** [comment] 2017-11-20 10:37
![image](https://user-images.githubusercontent.com/15725589/33014306-dd9b4fae-ce21-11e7-9c5e-bd61e2442836.png)
😢

**Comment by LinusBorg** [comment] 2017-11-20 10:43
whats your version of vue-cli?

**Comment by zslucky** [comment] 2017-11-20 11:08
Versions:

vue-cli: 2.9.1
os: mac 10.12.6
node: 6.11.0
npm: 3.10.10

I have added it in first comment

**Comment by LinusBorg** [comment] 2017-11-20 11:55
Oh right, sorry. Still can't reproduce this, though - those helpers are pre-registered in vue-cli, they don't even come from this template:

https://github.com/vuejs/vue-cli#pre-registered-handlebars-helpers

**Comment by LinusBorg** [comment] 2017-11-20 17:24
Closing as I can't reproduce, and if it's a bug, it's with vue.cli, not this template.

**Closed by LinusBorg** 2017-11-20 17:24 UTC
Labels: question
