### ISSUE TITLE
Default webpack config cannot support <img v-bind:src="url"> when url is a local image file

### ISSUE THREAD

**Issue by daneric** [vuejs-templates/webpack#199] opened 2016-07-18 10:19 UTC
I have an thumb collection like:
`thumbs = [`
`  '../assets/aaa.jpg',`
`  '../assets/bbb.jpg',`
`  '../assets/ccc.jpg'`
`]`
and template in .vue file like:
`<div v-for="thumb in thumbs">`
`    <img src="../assets/cate/aaa.jpg"><!-- can display normally -->`
`    <img :src="thumb"> <!-- get 404 error -->`
`</div>`
How do I change the webpack config file to fix this problem?
Plese help, thanks.

**Comment by chrisvfritz** [comment] 2016-07-19 01:36
Duplicate of https://github.com/vuejs-templates/webpack/issues/126.

**Closed by chrisvfritz** 2016-07-19 01:36 UTC

**Comment by daneric** [comment] 2016-07-19 01:46
Got it! Thanks a lot!
