### ISSUE TITLE
Generate multipage html.

### ISSUE THREAD

**Issue by iltegin** [vuejs-templates/webpack#176] opened 2016-06-27 12:59 UTC
This project awesome but not appropriate for multipage application beacuse only one html file generate.

**Comment by Gomah** [comment] 2016-06-27 14:38
You can implement [vue-router](https://github.com/vuejs/vue-router) for 'multipage' purpose, also check the issue #75 ;)

**Comment by chrisvfritz** [comment] 2016-06-27 15:15
I'd say this probably even qualifies as a duplicate of #75.

**Closed by chrisvfritz** 2016-06-27 15:15 UTC
