### ISSUE TITLE
HTML only hot reload a few tags deep

### ISSUE THREAD

**Issue by gbdematos** [vuejs-templates/webpack#1033] opened 2017-11-07 22:29 UTC
Editing something inside `<template></template>` hot reloads properly (not the entire page) as expected. And adding something like `<div><div><div>something</div></div></div>` (note the nested tags) also reloads properly. But... 

Then, after changing `something` to `something else`, it doesn't hot reload. I have to change anything in the template that is not in nested tags, or something in the script, to have it hot reload.

The limit I found is 3 tags deep. Anything less than that works normally.

I found that it currently has a html-webpack-plugin issue, so some aspects of html hot reloading are disabled, but is the behavior normal/intended and does it have anything to do with it?

I also tried it with a clean `vue init webpack`.

**Comment by LinusBorg** [comment] 2017-11-08 07:17
There's A Regression concerning HMR in Vue 2.5, but a fix is available. 

Please see this issue: https://github.com/vuejs/vue-loader/issues/1041#issuecomment-342689466

I will close this issue here because this problem, if it still exists, is with Vue itself, not this template.

**Closed** 2017-11-08 07:17 UTC
