### ISSUE TITLE
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin

### ISSUE THREAD

**Issue by ghost** [vuejs-templates/webpack#535] opened 2017-02-20 02:27 UTC
Thank you for an awesome template. 
I have run into this error with Windows 10, node 7.5.0 and npm 4.1.2. 
This error is with the boilerplate code unmodified  and running with NODE_ENV=production. 
There is no error with NODE_ENV=testing or development.
_________________________________________________________________________________________
``` 
ERROR  Failed to compile with 2 errors   

 error  in ./src/App.vue

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (C:\iTurbineIO\Projects\vue-webpack\node_modules\extract-text-webpack-plugin\loader.js:27:9)

 @ ./src/App.vue 3:0-335
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Hello.vue

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (C:\iTurbineIO\Projects\vue-webpack\node_modules\extract-text-webpack-plugin\loader.js:27:9)

 @ ./src/components/Hello.vue 3:0-345
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
```

**Comment by iTurbine1** [comment] 2017-02-20 16:11
I tried this template in NODE_ENV=development, testing and production with no issues:
[browserify](https://github.com/vuejs-templates/browserify)

**Comment by Lacroute** [comment] 2017-03-12 15:14
`NODE_ENV=development` fixed the problem for me too.

**Comment by Turqueso** [comment] 2017-03-17 22:04
Having same problem, @Lacroute where did you add `NODE_ENV=development`

**Comment by Lacroute** [comment] 2017-03-18 14:26
@Turqueso From command line `set NODE_ENV=development` and if you're on windows you should take a look at your environment variables ;)

**Comment by kerf007** [comment] 2017-03-28 09:26
Problem fixed for me too: `NODE_ENV=development`.
I added it in 'dev' script (for windows): `"dev": "cross-env NODE_ENV=development node build/dev-server.js"`

**Comment by Volcanic-Penguin** [comment] 2017-04-26 12:48
If an unmodified webpack template is giving errors I'd rather just use webpack-simple

**Comment by moshie** [comment] 2017-07-08 18:03
This is still an issue and setting `NODE_ENV=development` is not a fix... It's fundamental this template works setting the node environment to production

to replicate:
```
$ vue init webpack test
$ cd test/
$ npm install
$ NODE_ENV=production npm start
```

**Comment by 0123cf** [comment] 2017-07-09 03:07
Having same problem.  my get the same error on npm run build , ought to  where did  
add NODE_ENV=development ?  @moshie

**Comment by victorhazbun** [comment] 2017-07-22 06:42
Why this thing does not work on NODE_ENV=production but NODE_ENV=development can someone explain???

**Comment by srodriki** [comment] 2017-08-11 15:59
I can confirm the build does not work when NODE_ENV=production is set. 

In `build/utils.js` we find the generateLoaders function which seems to be using said plugin, as well as it's used in `build/webpack.prod.conf.js` 

```javascript
// generate loader string to be used with extract text plugin
  function generateLoaders (loader, loaderOptions) {
    var loaders = [cssLoader]
    if (loader) {
      loaders.push({
        loader: loader + '-loader',
        options: Object.assign({}, loaderOptions, {
          sourceMap: options.sourceMap
        })
      })
    }

    // Extract CSS when that option is specified
    // (which is the case during production build)
    if (options.extract) {
      return ExtractTextPlugin.extract({
        use: loaders,
        fallback: 'vue-style-loader'
      })
    } else {
      return ['vue-style-loader'].concat(loaders)
    }
  }
```

```javascript
// extract css into its own file
    new ExtractTextPlugin({
      filename: utils.assetsPath('css/[name].[contenthash].css')
    })
```

I haven't been able to find a solution yet (I'm pretty new on how webpack works) but I'll let everyone know if I ever find one.

**Comment by helaili** [comment] 2017-08-18 15:51
I found out that `webpack.prod.conf` was not loaded when `NODE_ENV === 'production'`. I've solved it as followed in `dev-server.js` : 

```js
var webpackConfig = process.env.NODE_ENV === 'testing' || 'production'
  ? require('./webpack.prod.conf')
  : require('./webpack.dev.conf')
```

**Comment by srodriki** [comment] 2017-08-19 21:02
@helaili thanks a lot for the fix! Hope your PR is merged soon! I also noticed vue's pwa template has also the same problem so it's likely your fix will help them too. If you don't mind, I might as well do it myself. 

Cheers!

**Comment by helaili** [comment] 2017-08-21 07:27
Sure @srodriki, go ahead.

**Comment by LinusBorg** [comment] 2017-11-01 18:13
I will close this since `dev-server.js` will be replaced with webpack-dev-server in the coming days (#975) - if this problem persists with the new setup, please open another issue and reference this one in it.

**Closed by LinusBorg** 2017-11-01 18:13 UTC

**Comment by lodemuyl** [comment] 2018-01-05 19:56
thanx a lot man

**Comment by jmbeach** [comment] 2018-05-03 13:03
I'm still experiencing this issue.
