### ISSUE TITLE
'fs' not working

### ISSUE THREAD

**Issue by tvld** [vuejs-templates/webpack#262] opened 2016-09-14 11:51 UTC
Suppose to reopen issue #91. Breaking bug I think

**Comment by tvld** [comment] 2016-09-14 12:02
Problem same ``for vue init webpack`` and ``vue init webpack-simple``

**Comment by LinusBorg** [comment] 2016-09-14 19:59
this is a webpack problem, googling this error message brought many results, the usual solution is appearantly to add this to the webpack conf:
```
node: {
  fs: "empty"
}
```

See here, for example: https://github.com/pugjs/pug-loader/issues/8#issuecomment-55568520

**Comment by tvld** [comment] 2016-09-14 20:26
yes.. I tried that,  and although webpack no longer complained, it still did not work...

 But you know what? I realized I was trying to use 'fs' in...the browser... oops... should that be the problem? fs in server makes more sense  ;)

**Comment by LinusBorg** [comment] 2016-09-15 06:15
That *might* be the problem as it can't work... 

Closing this as a "solution" was identified ;)

**Closed by LinusBorg** 2016-09-15 06:15 UTC

**Comment by chandrasekarb** [comment] 2017-05-12 13:46
`node: {
  fs: "empty"
}`

Using this above code error has been solved but 

          `fs.writeFile('/home/react-hello-world/test.txt', 'aaa', function(err) { alert(err); });`

`fs.writeFile` is not working please give any solution.

**Comment by LinusBorg** [comment] 2017-05-12 14:48
Well, you replaced `fs` with an empty module, so any `fs` methods will not work.

>ou cannot use `fs` in the browser, there is no solution to this, it's techincally impossible.

**Comment by elisandroesp** [comment] 2018-11-22 12:07
It's not impossible if you are on a CEP VM, like the HTML5 Adobe Extension do.
The problem is real

**Comment by LinusBorg** [comment] 2018-11-22 12:34
Well I don't really know what a CEP VM is, it's definitely not the usecase this template was built for. 

And generally this is a webpack problem, Vue won't solve that.

**Comment by elisandroesp** [comment] 2018-11-25 09:07
After a lot of tests, I've found a simple solution to use the nodejs on the chrome machine:
adding this to webpack.prod.conf.js allowed me to use your template to create Adobe extensions: 
`{  
...
 target: "node-webkit"
...
 }`

They run on a CEF, "Chromium Embedded Framework"  (My mistake: not a CEP, not a VM). http://code.google.com/p/chromiumembedded/
More info about Adobe CEP: 
https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_8.x/Documentation/CEP%208.0%20HTML%20Extension%20Cookbook.md#applications-integrated-with-cep
