### ISSUE TITLE
Getting error after creating project for the first time.

### ISSUE THREAD

**Issue by samuelwight** [vuejs-templates/webpack#139] opened 2016-05-25 16:58 UTC
I just created a project and I'm getting the error 'Cannot GET /' when I try to view localhost:8080. I didn't see any errors during installation or creation, and I haven't edited any files. Any tips on what might be wrong?

[Edit] I'm getting confirmation that webpack built correctly, but I get this error:

```
ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/vue-loader/lib/selector.js?type=style&index=0!./src/App.vue
Module build failed: TypeError: Cannot read property 'options' of undefined
    at Object.module.exports (/home/chronos/user/Downloads/testproject/node_modules/vue-loader/lib/style-rewriter.js:78:21)
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/vue-loader/lib/selector.js?type=style&index=0!./src/App.vue 4:14-189 13:2-17:4 14:20-195

ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-34da3196&scoped=true!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/Hello.vue
Module build failed: TypeError: Cannot read property 'options' of undefined
    at Object.module.exports (/home/chronos/user/Downloads/testproject/node_modules/vue-loader/lib/style-rewriter.js:78:21)
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-34da3196&scoped=true!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/Hello.vue 4:14-227 13:2-17:4 14:20-233
```

**Comment by yyx990803** [comment] 2016-05-25 17:52
This is caused by a bug in `vue-loader@8.5.1`, upgrade to `vue-loader@8.5.2` and it should be fixed.

**Closed by yyx990803** 2016-05-25 17:52 UTC
