### ISSUE TITLE
Unit test coverage includes the test code

### ISSUE THREAD

**Issue by unhealthy** [vuejs-templates/webpack#104] opened 2016-05-04 02:58 UTC
I generate a pure project using vue-cli@2.0 and run `npm run unit`.
The coverage report includes the statistic information of test code.
![unit_test_coverage](https://cloud.githubusercontent.com/assets/3315274/15004237/0a53db86-11e7-11e6-9a50-108233b6580e.png)

I can fix this problem by changing the code of `karma.config.js`:
```
// make sure isparta loader is applied before eslint
webpackConfig.module.preLoaders = webpackConfig.module.preLoaders || [];
webpackConfig.module.preLoaders.unshift({
    test: /\.js$/,
    loader: 'babel',
    exclude: [
        path.resolve('src/components/'),
        path.resolve('node_modules/'),
    ],

});
webpackConfig.module.preLoaders.unshift({
    test: /\.js$/,
    loader: 'isparta',
    include: path.resolve('src/'),
});
```

I wonder whether it's on purpose that including the coverage information of test code or it's just a mistake which need to be fixed.

**Comment by yyx990803** [comment] 2016-05-04 17:09
Hmm I'm not able to reproduce this with a fresh install. What's your OS/Node version?

**Comment by unhealthy** [comment] 2016-05-04 18:26
Sorry for the lack of information.
Os:Windows10
Node: 5.0

**Comment by yyx990803** [comment] 2016-05-04 18:58
The exclude pattern didn't work properly on Windows, it's fixed now.

**Closed by yyx990803** 2016-05-04 18:58 UTC

**Comment by unhealthy** [comment] 2016-05-05 03:12
Thanks very much!
