### ISSUE TITLE
Getting wrong breakpoints / lines in Chrome when using this template out-of-the-box

### ISSUE THREAD

**Issue by gebrits** [vuejs-templates/webpack#589] opened 2017-03-09 13:23 UTC
Using this template out-of-the-box I'm having issues with setting breakpoints in Chrome. Specifically: 

- setting a breakpoint doesn't stop at that point (nor anywhere else afaik) 
- some lines on which a breakpoint should be possible cannot be set. 

I'm running my dev env with `npm run dev`

This happens on both `.vue` as well as normal `.js`-files. 

Additionally, I thought this might be an issue with hot-reloading but it happens on a clean run of `npm run dev` as well as on consecutive runs. 

Is this a known issue? Any workarounds?

**Comment by gebrits** [comment] 2017-03-09 16:29
Investigating a bit further changing from `#cheap-module-eval-source-map` to `#cheap-module-source-map` seems to solve it for now. Leaving this open for a while to see how it goes.

**Comment by tsneed290** [comment] 2017-03-29 20:57
Had similar issues. Changed "#cheap-module-eval-source-map" to "#source-map" in webpack.dev.conf.js and I'm good now.

I also have this issue when running unit tests in Chrome browser (which uses #inline-source-map). Changing that to "#source-map" didn't seem to work. Hoping someone has a good workaround for that case :)

**Comment by TheMechanic** [comment] 2017-03-31 16:17
@tsneed290 : I'm not working with Vue currently, but i have a very similar config. I encoutered the same issues. the devTool param is not the same for dev and for test, because test use karma-sourcemap-loader, and I'm pretty sure that prevent to use the same config :(
For me breakpoints with "#inline-source-map" in test runs, but i have some weird behaviours, and no way to access variables in console, no mapping there...

**Comment by gebrits** [comment] 2017-03-31 18:24
@tsneed290 does "#source-map" give you the compiled down code using babel or the original?

**Comment by gebrits** [comment] 2017-03-31 18:24
wrong close

**Comment by dweremeichik** [comment] 2017-10-23 06:42
duplicate of #520?

**Closed** 2017-11-01 18:22 UTC
