### ISSUE TITLE
Hot reload has stopped working

### ISSUE THREAD

**Issue by boltonomous** [vuejs-templates/webpack#1054] opened 2017-11-13 16:48 UTC
I ran a fresh install of vue init webpack this morning, however hot-reloading doesn't seem to work anymore.

**Comment by LinusBorg** [comment] 2017-11-13 21:14
Just did a quick test, works for me. What's your environment? Inside a VM, a dropbox folder or something like that?

HMR has problems in various environments, in those situations you can maybe help yourself with the `poll` option:
https://github.com/vuejs-templates/webpack/blob/develop/template/config/index.js#L21

**Comment by LinusBorg** [comment] 2017-11-14 20:24
Closing since I doubt this is a problem of the template. If you can provide a reproduction of the issue, I'm happy to re-open.

**Closed** 2017-11-14 20:24 UTC

**Comment by tvld** [comment] 2017-11-15 15:15
Got the same issue: pure and fresh install on Ubuntu 17.04, all clean and new:
```
vue init webpack my-project
cd my-project
npm install
npm run dev
```
Changing "HelloWorld" does not hot reload.

**Comment by LinusBorg** [comment] 2017-11-15 15:50
* no VM?
* no dropbox or other service/tool "watching" the folder the project is in?
* special characters in the path? Webpack used to not like those as well ...

**Comment by tvld** [comment] 2017-11-15 15:53
- no VM, docker or whatever, just on the laptop )
- no other watchers
- ~/Websites/Company/websites/tomtest

**Comment by tvld** [comment] 2017-11-15 15:54
@boltonomous what OS you use?

**Comment by boltonomous** [comment] 2017-11-15 16:08
Sorry for the lack of reply...

* Mac OSX 10.12.2 
* VMs, watchers or special characters in the paths (other than underscores and dashes)
* Same behavior using Node v6.11.1/npm 3.10.10 AND 
* vue cli 2.9.1

However, I AM seeing it work now.  I think what may have thrown me off is that it is no longer automatically launching a browser.  I update HelloWorld.vue and am seeing it update in Chrome.

**Comment by LinusBorg** [comment] 2017-11-15 16:10
> I think what may have thrown me off is that it is no longer automatically launching a browser.

That has nothing to do with Hot Reloading.

You can turn this behaviour on again in `/config/index.js`

**Comment by tvld** [comment] 2017-11-15 16:16
Just double checked again, from scratch, and now with Chrome instead of Firefox... same isseu. No hot reload... Sorry reload stopped working. It worked for me in the past without  issues on my other pc

**Comment by boltonomous** [comment] 2017-11-15 16:19
Thanks @LinusBorg for setting me straight.  That works in my situation.

**Comment by LinusBorg** [comment] 2017-11-15 16:19
>  No hot reload... Sorry reload stopped working.

I don't understand what exactly stopped working now.

**Comment by tvld** [comment] 2017-11-15 16:21
> No hot reload... Sorry reload stopped working.
Just meant to say same, no hot module reload
In Chrome webdev console it says: ``[HMR] Waiting for update signal from WDS...``

**Comment by tvld** [comment] 2017-11-15 17:10
After _restarting my PC_, hot reload works as intended, so also with ``poll: false``.  To be sure, created a new project from scratch, number 10 today ;) and all is fine... 

So only thing I can say so far: try to restart PC if hot reload does not work...

**Comment by LinusBorg** [comment] 2017-11-15 17:45
The good old *"have you tried turning it off and on again?"* - never gets out of fashion :)

**Comment by tvld** [comment] 2017-11-15 17:57
And cheered too soon... stopped again :-(    I really dont know why...

**Comment by tvld** [comment] 2017-11-15 21:51
@LinusBorg  FYI ``sudo npm run dev`` does work, so it must be something in my system regarding to permissions. 
 I suppose you were right closing the issue here. But I still need to figure out how to solve this... maybe some group membership or something missing? Maybe because I downgraded from node v8 to v6 something was screwed up...? Anyway, if I find it, I will report )

**Comment by tvld** [comment] 2017-11-15 22:17
Seems I finally found it: my ``$cat /proc/sys/fs/inotify/max_user_watches`` was on ``8192``  and this helped me:

```
echo 100000 | sudo tee /proc/sys/fs/inotify/max_user_watches
```
Now Vue hot reload works without sudo and without poll ! ))))
Really closed ;))

**Comment by tesarwijaya** [comment] 2017-11-21 07:16
i have same issue with windows10 environment.
- OS Win10
- npm 3.10
- vue-cli 2.8.1
- fresh install

editing App.vue is triggering hot reload but when editting Hello.vue hot reload is not works.
i also tried run `npm run dev` using admin powershell but still not works.

**Comment by maitrungduc1410** [comment] 2018-07-27 04:01
I'm now using Ubuntu 16.04 LTS and the solution of @tvld works perfectly :100:

**Comment by CristalT** [comment] 2018-08-21 20:47
The solution of @tvld works for me in Xubuntu 18.04

**Comment by egorzot** [comment] 2018-09-01 05:26
@tvld thanks!!!!

**Comment by websebdev** [comment] 2018-09-03 19:33
Solution from @tvld also fixed the issue for me and I'm on a Ubuntu 18.04 vm. Does anyone have an idea of why this happens?
It's the second time that I need to fix it.

**Comment by CristalT** [comment] 2018-09-11 21:53
It happens to me using Quasar Framework, I fix it removing the temp directory that dev server generates, maybe could find a similiar solution with vue-cli

**Comment by markoaherrera** [comment] 2018-09-12 00:46
Hi, my 2 cents here, I'm using vue cli 3, so after a while and plenty of changes, HMR stops working so after reading this I closed the terminal window where I was executing "npm run serve", and it worked using a new terminal window, if it keeps happening I'll give the solution from @tvld a try, I'm using Ubuntu 16.04.

**Comment by p01ymath** [comment] 2018-11-23 11:30
@tvld You just saved my whole day! I won't forget your help ever lol!

**Comment by tvld** [comment] 2018-11-23 12:20
@p01ymath you're welcome... )

**Comment by Zicrael** [comment] 2018-12-05 13:19
@tvld lol, its work. Magic?:D

**Comment by claudiolcastro** [comment] 2019-03-08 13:05
@tvld  well done. thanks!

**Comment by cgillions** [comment] 2019-03-14 09:15
Still not working for me:

Ubuntu 18.04.2 LTS 
Webstorm 2018.3.5
Chrome Version 73.0.3683.75 (Official Build) (64-bit)

Tried restarting, increasing max watchers, disabling "Use safe write" in Webstorm.

When I run "npm run serve", the website loads and this line is output in the console:
"[HMR] Waiting for update signal from WDS..."

If I make changes in a Vue component and save, my terminal session re-compiles the code, but no changes are seen in Chrome.

**Comment by tvld** [comment] 2019-03-14 15:03
@cgillions  you see the changes if you Ctrl-F5 in Chrome?

**Comment by cgillions** [comment] 2019-03-14 16:39
@tvld - yes. 

After "I make changes in a Vue component and save, my terminal session re-compiles the code, but no changes are seen in Chrome", I can refresh Chrome and the changes appear.

**Comment by tvld** [comment] 2019-03-14 21:12
@cgillions then your problem must be not related to this thread. I would suggest to try other browser and check if your code has no sticky errors...

**Comment by ioanmeri** [comment] 2019-10-30 08:26
New Ubuntu user here and I was forgetting the **sudo** 
`sudo npm run dev`

**Comment by ttodua** [comment] 2020-10-11 11:20
**`set NODE_ENV=development`** might solve your problem.
