### ISSUE TITLE
CommonsChunkPlugin not work with require in .vue files

### ISSUE THREAD

**Issue by hanai** [vuejs-templates/webpack#543] opened 2017-02-22 09:35 UTC
I import `moment` module in 3 .vue files, but `moment` didn't be generated in vendor.js

https://github.com/hanai/test

<img width="1133" alt="jj" src="https://cloud.githubusercontent.com/assets/1222115/23209891/23818022-f936-11e6-9bf9-26bfc0f4b832.png">

**Comment by LinusBorg** [comment] 2017-02-22 10:11
Hello @hanai,,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted.


Thank you.

**Comment by hanai** [comment] 2017-02-22 11:39
repro add

**Comment by LinusBorg** [comment] 2017-02-22 11:48
thanks

**Comment by LinusBorg** [comment] 2017-02-22 12:04
That is working as expected. Since all 3 of your route components require `moment.js`, and its up to the visitor to decide which route to go to first, webpack has to put it into each of the async bundles.

if you want to extract dependencies that are shared amongst your extractred asynv bundles, you have to create another instance of the commonChunks Plugin:

I *think* it should look like this:
```
javascript
plugins: [
 // other plugins...,
  new webpack.optimize.CommonsChunkPlugin({
    name: 'commonsasync.js',
    async; 'commonsasync',
    min: 2,
  })
]
```

Coincidentally, I learned about this just yesterday through this article:

https://medium.com/@adamrackis/vendor-and-code-splitting-in-webpack-2-6376358f1923#.jyz1nf7v2

...and haven't tested it. Try it out and see if that works as intended.

**Comment by LinusBorg** [comment] 2017-02-23 09:40
@hanai If that solves your problem, please consider closing this issue.

**Closed** 2017-02-24 03:25 UTC
