### ISSUE TITLE
Linting in the "preLoader" phase breaks when using Jade templates

### ISSUE THREAD

**Issue by jbruni** [vuejs-templates/webpack#23] opened 2016-02-19 08:37 UTC
### Steps to reproduce:

- Create new project (https://github.com/vuejs-templates/webpack#usage)
```
$ npm install -g vue-cli
$ vue init webpack my-project
$ cd my-project
$ npm install
```

- Install jade deps (https://github.com/vuejs/vue-loader/blob/master/docs/configurations/pre-processors.md#templates)
```
$ npm install template-html-loader jade --save-dev
```

- Edit `src/components/Hello.vue`, transforming the template to jade syntax
```
<template lang="jade">
  div.hello
    h1.
      {{ msg }}
</template>
```

- Build
```
$ npm run build
```

### Result:

```
> my-project@ build /home/jbruni/TT/temp/my-project
> rimraf dist && cross-env NODE_ENV=production webpack --progress --hide-modules --config build/webpack.prod.conf.js

Hash: 831fadef5c178816535e  
Version: webpack 1.12.13
Time: 5146ms
                                       Asset       Size  Chunks             Chunk Names
                 app.1d3b2b4d38325cdb6c85.js    83.7 kB       0  [emitted]  app
    app.6b590370d011a33cd6d0437256238024.css  106 bytes       0  [emitted]  app
             app.1d3b2b4d38325cdb6c85.js.map     656 kB       0  [emitted]  app
app.6b590370d011a33cd6d0437256238024.css.map  303 bytes       0  [emitted]  app
                               ../index.html  242 bytes          [emitted]  

ERROR in ./~/vue-html-loader!./~/template-html-loader?raw&engine=jade!./~/vue-loader/lib/selector.js?type=template&index=0!./src/components/Hello.vue
Module build failed: TypeError: Cannot read property '0' of undefined
    at Object.module.exports.processComment (/home/jbruni/TT/temp/my-project/node_modules/espree/lib/comment-attachment.js:107:133)
    at Parser.esprimaFinishNode (/home/jbruni/TT/temp/my-project/node_modules/espree/espree.js:185:27)
    at Parser.finishNode (/home/jbruni/TT/temp/my-project/node_modules/espree/espree.js:234:34)
    at Parser.pp.parseIdent (/home/jbruni/TT/temp/my-project/node_modules/acorn/dist/acorn.js:673:15)
    at Parser.pp.parseExprAtom (/home/jbruni/TT/temp/my-project/node_modules/acorn/dist/acorn.js:276:21)
    at Parser.pp.parseExprSubscripts (/home/jbruni/TT/temp/my-project/node_modules/acorn/dist/acorn.js:216:19)
    at Parser.pp.parseMaybeUnary (/home/jbruni/TT/temp/my-project/node_modules/acorn/dist/acorn.js:197:19)
    at Parser.pp.parseExprOps (/home/jbruni/TT/temp/my-project/node_modules/acorn/dist/acorn.js:151:19)
    at Parser.pp.parseMaybeConditional (/home/jbruni/TT/temp/my-project/node_modules/acorn/dist/acorn.js:133:19)
    at Parser.pp.parseMaybeAssign (/home/jbruni/TT/temp/my-project/node_modules/acorn/dist/acorn.js:110:19)
    at Parser.pp.parseExpression (/home/jbruni/TT/temp/my-project/node_modules/acorn/dist/acorn.js:86:19)
    at Parser.pp.parseStatement (/home/jbruni/TT/temp/my-project/node_modules/acorn/dist/acorn.js:1750:23)
    at Parser.pp.parseTopLevel (/home/jbruni/TT/temp/my-project/node_modules/acorn/dist/acorn.js:1666:21)
    at Parser.parseTopLevel (/home/jbruni/TT/temp/my-project/node_modules/espree/espree.js:274:30)
    at Parser.parse (/home/jbruni/TT/temp/my-project/node_modules/acorn/dist/acorn.js:1636:17)
    at Object.parse (/home/jbruni/TT/temp/my-project/node_modules/acorn/dist/acorn.js:905:44)
    at reallyParse (/home/jbruni/TT/temp/my-project/node_modules/acorn-globals/index.js:30:18)
    at findGlobals (/home/jbruni/TT/temp/my-project/node_modules/acorn-globals/index.js:45:11)
    at addWith (/home/jbruni/TT/temp/my-project/node_modules/with/index.js:44:28)
    at parse (/home/jbruni/TT/temp/my-project/node_modules/jade/lib/index.js:149:9)
    at Object.exports.compile (/home/jbruni/TT/temp/my-project/node_modules/jade/lib/index.js:205:16)
    at handleTemplateCache (/home/jbruni/TT/temp/my-project/node_modules/jade/lib/index.js:174:25)
    at Object.exports.render (/home/jbruni/TT/temp/my-project/node_modules/jade/lib/index.js:349:10)
    at Object.exports.render (/home/jbruni/TT/temp/my-project/node_modules/jade/lib/index.js:335:21)
    at Function.exports.jade.render (/home/jbruni/TT/temp/my-project/node_modules/consolidate/lib/consolidate.js:182:10)
    at Object.module.exports (/home/jbruni/TT/temp/my-project/node_modules/template-html-loader/index.js:32:20)
 @ ./src/components/Hello.vue 3:19-166
Child html-webpack-plugin for "../index.html":
    
Child extract-text-webpack-plugin:
```

**Comment by jbruni** [comment] 2016-02-19 08:43
If you do exactly the same steps above, but instead of using the latest template, you use a past version, it will work. As I have done a tiny pull request recently, GitHub automatically created a fork. The master branch of my fork "is 16 commits behind vuejs-templates:master" at this moment. So, in the "steps to reproduce" above, you can simply change `vue init` call to:

```
$ vue init jbruni/webpack my-project
```

Performing the exact same steps, this is the sucessfull result:

```
> my-project@ build /home/jbruni/TT/boo/my-project
> rimraf dist && webpack --progress --hide-modules --config build/webpack.prod.conf.js

Hash: b08bd5b8691a16fbc7a1  
Version: webpack 1.12.13
Time: 4838ms
                                       Asset       Size  Chunks             Chunk Names
                 app.98c111ddf2117c6910d3.js    83.6 kB       0  [emitted]  app
    app.6b590370d011a33cd6d0437256238024.css  106 bytes       0  [emitted]  app
             app.98c111ddf2117c6910d3.js.map     656 kB       0  [emitted]  app
app.6b590370d011a33cd6d0437256238024.css.map  303 bytes       0  [emitted]  app
                               ../index.html  290 bytes          [emitted]  
Child extract-text-webpack-plugin:
```

**Comment by jbruni** [comment] 2016-02-19 09:13
Hey... I just found that if I **remove the preLoaders** from `webpack.base.conf.js`, the result is successful.

And if I add `!eslint` back to the loaders, I get the linting back, up & running, and the result is also successful.

```
      {
        test: /\.vue$/,
        loader: 'vue!eslint'
      },
      {
        test: /\.js$/,
        loader: 'babel!eslint',
        exclude: /node_modules/
      },
```

So, the issue is related to linting in the "preLoader" phase.

I've read the rationale at http://vuejs.github.io/vue-loader/workflow/linting.html, but I will revert https://github.com/vuejs-templates/webpack/commit/bab75ff42a34b25237f83b89033db7df5865b0d0 in my project until this is resolved.

Thank you.

**Comment by yyx990803** [comment] 2016-02-19 18:36
Thanks for the detailed report. So after investigation, this is actually caused by ESLint/espree monkey-patching Acorn (which is in turn depended by Jade)... it has already been fixed in espree and should expect a new patch release any time: https://github.com/eslint/espree/issues/250

**Closed by yyx990803** 2016-02-19 18:36 UTC

**Comment by yyx990803** [comment] 2016-02-19 19:21
espree@3.0.2 is out, update your eslint and it should work :)

**Comment by jbruni** [comment] 2016-02-19 21:38
Indeed. It works now. Great! Thanks.

Meanwhile, I've faced another (unrelated) issue, which made me remove `"plugins": ["transform-runtime"]` from `.babelrc` (at least temporarily, while they don't fix it): https://phabricator.babeljs.io/T7127
